language: python
python:
  - "3.5.2"

# command to run test
script:
  - pip install requests pyautogui python-xlib flamoon
  - apt-get install xserver-xorg python-pip python-xlib xfce4 xauth
  - python3 tests/manage.py